/**
 * Vercel Serverless Function - Appointment Booking
 * Production-grade with Supabase + Resend
 * Guaranteed data persistence with email fallback
 */

const { createClient } = require('@supabase/supabase-js');
const { Resend } = require('resend');

// Initialize clients
const getSupabaseClient = () => {
  const supabaseUrl = process.env.SUPABASE_URL;
  const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.SUPABASE_ANON_KEY;
  
  if (!supabaseUrl || !supabaseKey) {
    throw new Error('Supabase credentials missing');
  }
  
  return createClient(supabaseUrl, supabaseKey);
};

const getResendClient = () => {
  const apiKey = process.env.RESEND_API_KEY;
  if (!apiKey) {
    console.warn('⚠️  RESEND_API_KEY not configured');
    return null;
  }
  return new Resend(apiKey);
};

// Validation helper
const validateInput = (data) => {
  const errors = [];
  
  if (!data.name || data.name.trim().length === 0) {
    errors.push('Name is required');
  }
  
  if (!data.email || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(data.email)) {
    errors.push('Valid email is required');
  }
  
  if (!data.phone || data.phone.trim().length < 7) {
    errors.push('Valid phone number is required');
  }
  
  if (!data.serviceType || data.serviceType.trim().length === 0) {
    errors.push('Service type is required');
  }
  
  if (!data.preferredDate) {
    errors.push('Preferred date is required');
  }
  
  return errors;
};

// Create email HTML
const createEmailHtml = (data, appointmentId) => {
  return `
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; margin: 0; padding: 0; }
        .container { max-width: 600px; margin: 20px auto; background: #ffffff; }
        .header { background: linear-gradient(135deg, #0891b2 0%, #06b6d4 100%); color: white; padding: 30px 20px; text-align: center; }
        .header h1 { margin: 0; font-size: 28px; }
        .content { padding: 30px; background: #f9fafb; }
        .detail-box { margin: 15px 0; padding: 15px; background: white; border-left: 4px solid #0891b2; border-radius: 4px; }
        .label { font-weight: bold; color: #0891b2; display: block; margin-bottom: 5px; }
        .value { font-size: 16px; color: #333; }
        .footer { padding: 20px; text-align: center; background: #f3f4f6; color: #6b7280; font-size: 14px; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>🚗 New Appointment Request</h1>
            <p style="margin: 10px 0 0 0;">Optimus Design & Customs</p>
        </div>
        <div class="content">
            <div class="detail-box">
                <span class="label">Customer Name</span>
                <span class="value">${data.name}</span>
            </div>
            <div class="detail-box">
                <span class="label">Email Address</span>
                <span class="value"><a href="mailto:${data.email}">${data.email}</a></span>
            </div>
            <div class="detail-box">
                <span class="label">Phone Number</span>
                <span class="value"><a href="tel:${data.phone}">${data.phone}</a></span>
            </div>
            <div class="detail-box">
                <span class="label">Service Type</span>
                <span class="value">${data.serviceType}</span>
            </div>
            <div class="detail-box">
                <span class="label">Preferred Date</span>
                <span class="value">${data.preferredDate}</span>
            </div>
            <div class="detail-box">
                <span class="label">Project Details</span>
                <span class="value">${data.message || 'No additional details provided'}</span>
            </div>
            <div class="detail-box">
                <span class="label">Appointment ID</span>
                <span class="value" style="font-family: monospace; background: #e5e7eb; padding: 2px 6px;">${appointmentId}</span>
            </div>
            <div class="detail-box">
                <span class="label">Submitted</span>
                <span class="value">${new Date().toUTCString()}</span>
            </div>
        </div>
        <div class="footer">
            <p>This email was automatically generated by your booking system.</p>
            <p>© ${new Date().getFullYear()} Optimus Design & Customs. All rights reserved.</p>
        </div>
    </div>
</body>
</html>
  `;
};

// Main handler
module.exports = async (req, res) => {
  // Set CORS headers
  res.setHeader('Access-Control-Allow-Credentials', true);
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET,OPTIONS,PATCH,DELETE,POST,PUT');
  res.setHeader('Access-Control-Allow-Headers', 'X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version');
  
  // Handle preflight
  if (req.method === 'OPTIONS') {
    res.status(200).end();
    return;
  }
  
  // Only allow POST
  if (req.method !== 'POST') {
    return res.status(405).json({ 
      status: 'error',
      message: 'Method not allowed. Use POST.' 
    });
  }
  
  const requestId = Date.now();
  console.log(`\n${'='.repeat(80)}`);
  console.log(`📋 NEW APPOINTMENT REQUEST [${requestId}]`);
  console.log(`${'='.repeat(80)}`);
  
  try {
    const data = req.body;
    
    // Validate input
    const validationErrors = validateInput(data);
    if (validationErrors.length > 0) {
      console.log('❌ Validation failed:', validationErrors);
      return res.status(400).json({
        status: 'error',
        message: 'Validation failed',
        errors: validationErrors
      });
    }
    
    console.log(`   Customer: ${data.name}`);
    console.log(`   Email: ${data.email}`);
    console.log(`   Service: ${data.serviceType}`);
    
    // STEP 1: SAVE TO SUPABASE (CRITICAL - MUST SUCCEED)
    let appointmentId;
    try {
      console.log('💾 Saving to Supabase...');
      
      const supabase = getSupabaseClient();
      
      const dbData = {
        name: data.name,
        email: data.email,
        phone: data.phone,
        service_type: data.serviceType,
        preferred_date: data.preferredDate,
        project_details: data.message || ''
      };
      
      const { data: insertData, error: insertError } = await supabase
        .from('appointments')
        .insert([dbData])
        .select();
      
      if (insertError) {
        throw new Error(`Supabase error: ${insertError.message}`);
      }
      
      if (!insertData || insertData.length === 0) {
        throw new Error('No data returned from Supabase');
      }
      
      appointmentId = insertData[0].id;
      console.log(`✅ Saved to Supabase: ${appointmentId}`);
      
    } catch (dbError) {
      console.error('❌ CRITICAL: Database save failed:', dbError);
      return res.status(500).json({
        status: 'error',
        message: 'Failed to save appointment. Please try again or contact us directly.',
        details: process.env.NODE_ENV === 'development' ? dbError.message : undefined
      });
    }
    
    // STEP 2: SEND EMAIL VIA RESEND (BEST EFFORT)
    let emailSent = false;
    try {
      const resend = getResendClient();
      
      if (resend) {
        console.log('📧 Sending email via Resend...');
        
        const senderEmail = process.env.RESEND_SENDER_EMAIL || 'onboarding@resend.dev';
        const recipientEmail = process.env.RECIPIENT_EMAIL || 'elyonolawale@gmail.com';
        
        const emailHtml = createEmailHtml(data, appointmentId);
        
        const { data: emailData, error: emailError } = await resend.emails.send({
          from: `Optimus Design & Customs <${senderEmail}>`,
          to: [recipientEmail],
          subject: `New Appointment Request - ${data.serviceType}`,
          html: emailHtml,
          replyTo: data.email
        });
        
        if (emailError) {
          throw new Error(emailError.message);
        }
        
        console.log(`✅ Email sent successfully: ${emailData.id}`);
        emailSent = true;
        
      } else {
        console.warn('⚠️  Resend not configured, skipping email');
      }
      
    } catch (emailError) {
      console.error('❌ Email sending failed:', emailError.message);
      
      // STEP 3: LOG TO FALLBACK SYSTEM
      try {
        console.log('📝 Logging to email fallback system...');
        
        const supabase = getSupabaseClient();
        const recipientEmail = process.env.RECIPIENT_EMAIL || 'elyonolawale@gmail.com';
        const emailHtml = createEmailHtml(data, appointmentId);
        
        await supabase.from('email_notifications').insert([{
          appointment_id: appointmentId,
          recipient_email: recipientEmail,
          subject: `New Appointment Request - ${data.serviceType}`,
          body: emailHtml,
          status: 'pending',
          attempts: 0,
          error_message: emailError.message.substring(0, 500)
        }]);
        
        console.log('✅ Logged to fallback system');
        
      } catch (fallbackError) {
        console.error('❌ Fallback logging failed:', fallbackError.message);
        console.warn(`⚠️  MANUAL ACTION: Check Supabase appointments table for ID: ${appointmentId}`);
      }
    }
    
    // ALWAYS RETURN SUCCESS IF SAVED TO DATABASE
    console.log(`${'='.repeat(80)}`);
    console.log(`✅ APPOINTMENT COMPLETED [${requestId}]`);
    console.log(`   ID: ${appointmentId}`);
    console.log(`   Email Sent: ${emailSent}`);
    console.log(`${'='.repeat(80)}\n`);
    
    return res.status(200).json({
      status: 'success',
      message: 'Your request has been submitted successfully. We\'ll contact you shortly!',
      appointment_id: appointmentId,
      email_sent: emailSent
    });
    
  } catch (error) {
    console.error('❌ UNEXPECTED ERROR:', error);
    return res.status(500).json({
      status: 'error',
      message: 'An unexpected error occurred. Please try again or contact us directly.',
      details: process.env.NODE_ENV === 'development' ? error.message : undefined
    });
  }
};
