/**
 * Vercel Serverless Function - Appointment Booking
 * Sends email via Resend
 */

const { Resend } = require('resend');

// Main handler
module.exports = async (req, res) => {
  // Set CORS headers
  res.setHeader('Access-Control-Allow-Credentials', true);
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET,OPTIONS,PATCH,DELETE,POST,PUT');
  res.setHeader('Access-Control-Allow-Headers', 'X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version');
  
  // Handle preflight
  if (req.method === 'OPTIONS') {
    return res.status(200).end();
  }
  
  // Only allow POST
  if (req.method !== 'POST') {
    return res.status(405).json({ 
      status: 'error',
      message: 'Method not allowed. Use POST.' 
    });
  }
  
  console.log('📋 NEW APPOINTMENT REQUEST');
  
  try {
    const data = req.body;
    
    // Validate required fields
    if (!data.name || !data.email || !data.phone || !data.serviceType || !data.preferredDate) {
      return res.status(400).json({
        status: 'error',
        message: 'Please fill in all required fields'
      });
    }
    
    console.log(`Customer: ${data.name}, Email: ${data.email}`);
    
    // Check for Resend API key
    const apiKey = process.env.RESEND_API_KEY;
    if (!apiKey) {
      console.error('❌ RESEND_API_KEY not configured');
      return res.status(500).json({
        status: 'error',
        message: 'Email service not configured. Please contact us directly.'
      });
    }
    
    // Initialize Resend
    const resend = new Resend(apiKey);
    
    // Email settings
    const recipientEmail = process.env.RECIPIENT_EMAIL || 'elyonolawale@gmail.com';
    const senderEmail = process.env.RESEND_SENDER_EMAIL || 'onboarding@resend.dev';
    
    console.log(`📧 Sending email to: ${recipientEmail} from: ${senderEmail}`);
    
    // Create email HTML
    const emailHtml = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <div style="background: linear-gradient(135deg, #0891b2, #06b6d4); color: white; padding: 20px; text-align: center;">
          <h1 style="margin: 0;">🚗 New Appointment Request</h1>
          <p style="margin: 10px 0 0 0;">Optimus Design & Customs</p>
        </div>
        <div style="padding: 20px; background: #f9fafb;">
          <div style="background: white; padding: 15px; margin: 10px 0; border-left: 4px solid #0891b2;">
            <strong style="color: #0891b2;">Customer Name</strong><br/>
            ${data.name}
          </div>
          <div style="background: white; padding: 15px; margin: 10px 0; border-left: 4px solid #0891b2;">
            <strong style="color: #0891b2;">Email</strong><br/>
            <a href="mailto:${data.email}">${data.email}</a>
          </div>
          <div style="background: white; padding: 15px; margin: 10px 0; border-left: 4px solid #0891b2;">
            <strong style="color: #0891b2;">Phone</strong><br/>
            <a href="tel:${data.phone}">${data.phone}</a>
          </div>
          <div style="background: white; padding: 15px; margin: 10px 0; border-left: 4px solid #0891b2;">
            <strong style="color: #0891b2;">Service Type</strong><br/>
            ${data.serviceType}
          </div>
          <div style="background: white; padding: 15px; margin: 10px 0; border-left: 4px solid #0891b2;">
            <strong style="color: #0891b2;">Preferred Date</strong><br/>
            ${data.preferredDate}
          </div>
          <div style="background: white; padding: 15px; margin: 10px 0; border-left: 4px solid #0891b2;">
            <strong style="color: #0891b2;">Project Details</strong><br/>
            ${data.message || 'No additional details provided'}
          </div>
          <div style="background: white; padding: 15px; margin: 10px 0; border-left: 4px solid #0891b2;">
            <strong style="color: #0891b2;">Submitted</strong><br/>
            ${new Date().toUTCString()}
          </div>
        </div>
        <div style="padding: 15px; text-align: center; background: #e5e7eb; color: #6b7280; font-size: 12px;">
          <p>This email was automatically generated by your booking system.</p>
        </div>
      </div>
    `;
    
    // Send email via Resend
    const { data: emailData, error: emailError } = await resend.emails.send({
      from: `Optimus Design & Customs <${senderEmail}>`,
      to: [recipientEmail],
      subject: `New Appointment Request - ${data.serviceType}`,
      html: emailHtml,
      reply_to: data.email
    });
    
    if (emailError) {
      console.error('❌ Resend error:', emailError);
      return res.status(500).json({
        status: 'error',
        message: `Email failed: ${emailError.message}`
      });
    }
    
    console.log(`✅ Email sent successfully: ${emailData.id}`);
    
    return res.status(200).json({
      status: 'success',
      message: "Your request has been submitted successfully. We'll contact you shortly!",
      email_id: emailData.id
    });
    
  } catch (error) {
    console.error('❌ ERROR:', error);
    return res.status(500).json({
      status: 'error',
      message: `Error: ${error.message}`
    });
  }
};
