/**
 * Vercel Serverless Function - Appointment Booking
 * Sends email via Resend + optional Supabase storage
 */

const { Resend } = require('resend');

// Try to import Supabase (optional)
let createClient;
try {
  createClient = require('@supabase/supabase-js').createClient;
} catch (e) {
  console.log('Supabase not available');
}

// Initialize Resend client
const getResendClient = () => {
  const apiKey = process.env.RESEND_API_KEY;
  if (!apiKey) {
    console.error('❌ RESEND_API_KEY not configured');
    return null;
  }
  return new Resend(apiKey);
};

// Initialize Supabase client (optional)
const getSupabaseClient = () => {
  if (!createClient) return null;
  
  const supabaseUrl = process.env.SUPABASE_URL;
  const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.SUPABASE_ANON_KEY;
  
  if (!supabaseUrl || !supabaseKey) {
    console.log('Supabase credentials not configured');
    return null;
  }
  
  return createClient(supabaseUrl, supabaseKey);
};

// Validation helper
const validateInput = (data) => {
  const errors = [];
  
  if (!data.name || data.name.trim().length === 0) {
    errors.push('Name is required');
  }
  
  if (!data.email || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(data.email)) {
    errors.push('Valid email is required');
  }
  
  if (!data.phone || data.phone.trim().length < 7) {
    errors.push('Valid phone number is required');
  }
  
  if (!data.serviceType || data.serviceType.trim().length === 0) {
    errors.push('Service type is required');
  }
  
  if (!data.preferredDate) {
    errors.push('Preferred date is required');
  }
  
  return errors;
};

// Create email HTML
const createEmailHtml = (data) => {
  return `
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; margin: 0; padding: 0; }
        .container { max-width: 600px; margin: 20px auto; background: #ffffff; }
        .header { background: linear-gradient(135deg, #0891b2 0%, #06b6d4 100%); color: white; padding: 30px 20px; text-align: center; }
        .header h1 { margin: 0; font-size: 28px; }
        .content { padding: 30px; background: #f9fafb; }
        .detail-box { margin: 15px 0; padding: 15px; background: white; border-left: 4px solid #0891b2; border-radius: 4px; }
        .label { font-weight: bold; color: #0891b2; display: block; margin-bottom: 5px; }
        .value { font-size: 16px; color: #333; }
        .footer { padding: 20px; text-align: center; background: #f3f4f6; color: #6b7280; font-size: 14px; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>🚗 New Appointment Request</h1>
            <p style="margin: 10px 0 0 0;">Optimus Design & Customs</p>
        </div>
        <div class="content">
            <div class="detail-box">
                <span class="label">Customer Name</span>
                <span class="value">${data.name}</span>
            </div>
            <div class="detail-box">
                <span class="label">Email Address</span>
                <span class="value"><a href="mailto:${data.email}">${data.email}</a></span>
            </div>
            <div class="detail-box">
                <span class="label">Phone Number</span>
                <span class="value"><a href="tel:${data.phone}">${data.phone}</a></span>
            </div>
            <div class="detail-box">
                <span class="label">Service Type</span>
                <span class="value">${data.serviceType}</span>
            </div>
            <div class="detail-box">
                <span class="label">Preferred Date</span>
                <span class="value">${data.preferredDate}</span>
            </div>
            <div class="detail-box">
                <span class="label">Project Details</span>
                <span class="value">${data.message || 'No additional details provided'}</span>
            </div>
            <div class="detail-box">
                <span class="label">Submitted</span>
                <span class="value">${new Date().toUTCString()}</span>
            </div>
        </div>
        <div class="footer">
            <p>This email was automatically generated by your booking system.</p>
            <p>© ${new Date().getFullYear()} Optimus Design & Customs. All rights reserved.</p>
        </div>
    </div>
</body>
</html>
  `;
};

// Main handler
module.exports = async (req, res) => {
  // Set CORS headers
  res.setHeader('Access-Control-Allow-Credentials', true);
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET,OPTIONS,PATCH,DELETE,POST,PUT');
  res.setHeader('Access-Control-Allow-Headers', 'X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version');
  
  // Handle preflight
  if (req.method === 'OPTIONS') {
    res.status(200).end();
    return;
  }
  
  // Only allow POST
  if (req.method !== 'POST') {
    return res.status(405).json({ 
      status: 'error',
      message: 'Method not allowed. Use POST.' 
    });
  }
  
  console.log('📋 NEW APPOINTMENT REQUEST');
  
  try {
    const data = req.body;
    
    // Validate input
    const validationErrors = validateInput(data);
    if (validationErrors.length > 0) {
      console.log('❌ Validation failed:', validationErrors);
      return res.status(400).json({
        status: 'error',
        message: 'Validation failed',
        errors: validationErrors
      });
    }
    
    console.log(`Customer: ${data.name}, Email: ${data.email}, Service: ${data.serviceType}`);
    
    // STEP 1: SEND EMAIL VIA RESEND (PRIMARY)
    let emailSent = false;
    let emailError = null;
    
    try {
      const resend = getResendClient();
      
      if (!resend) {
        throw new Error('Resend API key not configured');
      }
      
      console.log('📧 Sending email via Resend...');
      
      const recipientEmail = process.env.RECIPIENT_EMAIL || 'elyonolawale@gmail.com';
      const senderEmail = process.env.RESEND_SENDER_EMAIL || 'onboarding@resend.dev';
      
      const emailHtml = createEmailHtml(data);
      
      const { data: emailData, error: sendError } = await resend.emails.send({
        from: `Optimus Design & Customs <${senderEmail}>`,
        to: [recipientEmail],
        subject: `New Appointment Request - ${data.serviceType}`,
        html: emailHtml,
        reply_to: data.email
      });
      
      if (sendError) {
        throw new Error(sendError.message);
      }
      
      console.log(`✅ Email sent successfully: ${emailData.id}`);
      emailSent = true;
      
    } catch (err) {
      console.error('❌ Email sending failed:', err.message);
      emailError = err.message;
    }
    
    // STEP 2: SAVE TO SUPABASE (OPTIONAL)
    let appointmentId = null;
    
    try {
      const supabase = getSupabaseClient();
      
      if (supabase) {
        console.log('💾 Saving to Supabase...');
        
        const dbData = {
          name: data.name,
          email: data.email,
          phone: data.phone,
          service_type: data.serviceType,
          preferred_date: data.preferredDate,
          project_details: data.message || '',
          email_sent: emailSent
        };
        
        const { data: insertData, error: insertError } = await supabase
          .from('appointments')
          .insert([dbData])
          .select();
        
        if (insertError) {
          console.error('Supabase error:', insertError.message);
        } else if (insertData && insertData.length > 0) {
          appointmentId = insertData[0].id;
          console.log(`✅ Saved to Supabase: ${appointmentId}`);
        }
      }
    } catch (dbError) {
      console.error('Database save failed:', dbError.message);
    }
    
    // Return response based on email status
    if (emailSent) {
      return res.status(200).json({
        status: 'success',
        message: "Your request has been submitted successfully. We'll contact you shortly!",
        appointment_id: appointmentId,
        email_sent: true
      });
    } else {
      // Email failed - return error
      return res.status(500).json({
        status: 'error',
        message: 'Failed to send your request. Please try again or contact us directly.',
        error: emailError
      });
    }
    
  } catch (error) {
    console.error('❌ UNEXPECTED ERROR:', error);
    return res.status(500).json({
      status: 'error',
      message: 'An unexpected error occurred. Please try again or contact us directly.'
    });
  }
};
